<?php

use App\Http\Controllers\Admin\AbandonedCartController;
use App\Http\Controllers\Admin\ApprovalCenterController;
use App\Http\Controllers\Admin\CustomerManagementController;
use App\Http\Controllers\Admin\CategoryRequestController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MarketingController;
use App\Http\Controllers\Admin\OperationsController;
use App\Http\Controllers\Admin\OrderWorkflowController;
use App\Http\Controllers\Admin\SellerManagementController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\SettlementReconciliationController;
use App\Http\Controllers\Admin\ShippingLabelController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminProductController;
use App\Http\Controllers\Auth\AdminAuthController;
use App\Http\Controllers\Auth\CustomerAuthController;
use App\Http\Controllers\Auth\GoogleAuthController;
use App\Http\Controllers\Auth\SellerAuthController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CartRecoveryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CookieConsentController;
use App\Http\Controllers\Seller\CategoryController as SellerCategoryController;
use App\Http\Controllers\Seller\DashboardController as SellerDashboardController;
use App\Http\Controllers\Seller\EarningsController as SellerEarningsController;
use App\Http\Controllers\Seller\InventoryController as SellerInventoryController;
use App\Http\Controllers\Seller\ModuleController as SellerModuleController;
use App\Http\Controllers\Seller\OnboardingController as SellerOnboardingController;
use App\Http\Controllers\Seller\OrderController as SellerOrderController;
use App\Http\Controllers\Seller\ProductController as SellerProductController;
use App\Http\Controllers\Seller\SettlementController as SellerSettlementController;
use App\Http\Controllers\SeoController;
use App\Http\Controllers\StorefrontController;
use Illuminate\Support\Facades\Route;

Route::get('/', [StorefrontController::class, 'home'])->name('home');
Route::get('/robots.txt', [SeoController::class, 'robots'])->name('robots');
Route::get('/sitemap.xml', [SeoController::class, 'sitemap'])->name('sitemap');
Route::get('/shop', [StorefrontController::class, 'shop'])->name('shop');
Route::get('/search', [StorefrontController::class, 'search'])->name('search');
Route::post('/location', [StorefrontController::class, 'storeLocation'])->name('location.store');
Route::delete('/location', [StorefrontController::class, 'clearLocation'])->name('location.clear');
Route::get('/departments/{slug}', [StorefrontController::class, 'department'])->name('department.show');
Route::get('/category/{slug}', [StorefrontController::class, 'category'])->name('category.show');
Route::get('/collections/{collection:slug}', [StorefrontController::class, 'collection'])->name('collections.show');
Route::get('/stores/{vendor:slug}', [StorefrontController::class, 'seller'])->name('stores.show');
Route::get('/products', [StorefrontController::class, 'shop'])->name('products.index');
Route::get('/products/{slug}', [StorefrontController::class, 'product'])->name('products.show');
Route::view('/return-refund-policy', 'policies.return-refund')->name('policies.return-refund');
Route::view('/cookie-policy', 'policies.cookie')->name('policies.cookie');
Route::post('/cookie-consent/essential', [CookieConsentController::class, 'store'])->name('cookie-consent.essential.store');
Route::redirect('/seller', '/seller/login')->name('seller');
Route::get('/admin', [AdminAuthController::class, 'entry'])->name('admin');
Route::get('/admin/login', [AdminAuthController::class, 'showLogin'])->name('admin.login');
Route::post('/admin/login', [AdminAuthController::class, 'login'])->name('admin.login.store');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [CustomerAuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [CustomerAuthController::class, 'login'])->name('login.store');
    Route::get('/register', [CustomerAuthController::class, 'showRegister'])->name('register');
    Route::post('/register', [CustomerAuthController::class, 'register'])->name('register.store');
    Route::get('/seller/login', [SellerAuthController::class, 'showLogin'])->name('seller.login');
    Route::post('/seller/login', [SellerAuthController::class, 'login'])->name('seller.login.store');
    Route::get('/seller/register', [SellerAuthController::class, 'showRegister'])->name('seller.register');
    Route::post('/seller/register', [SellerAuthController::class, 'register'])->name('seller.register.store');
    Route::get('/seller/forgot-password', [SellerAuthController::class, 'showForgotPassword'])->name('seller.password.request');
    Route::post('/seller/forgot-password', [SellerAuthController::class, 'sendResetLink'])->name('seller.password.email');
    Route::get('/seller/reset-password/{token}', [SellerAuthController::class, 'showResetPassword'])->name('seller.password.reset');
    Route::post('/seller/reset-password', [SellerAuthController::class, 'resetPassword'])->name('seller.password.update');
});

Route::get('/login/google', [GoogleAuthController::class, 'redirect'])->middleware('guest')->name('login.google');
Route::get('/login/google/callback', [GoogleAuthController::class, 'callback'])->middleware('guest')->name('login.google.callback');
Route::get('/seller/auth/google', [SellerAuthController::class, 'redirect'])->middleware('guest')->name('seller.auth.google');
Route::get('/seller/auth/google/callback', [SellerAuthController::class, 'callback'])->middleware('guest')->name('seller.auth.google.callback');
Route::post('/seller/onboarding/payment/webhook', [SellerOnboardingController::class, 'webhook'])->name('seller.onboarding.payment.webhook');
Route::get('/cart', [CartController::class, 'show'])->name('cart.empty');
Route::get('/cart/recover/{token}', CartRecoveryController::class)->middleware('signed')->name('cart.recover');
Route::post('/cart', [CartController::class, 'store'])->name('cart.store');
Route::patch('/cart/{key}', [CartController::class, 'update'])->name('cart.update');
Route::delete('/cart/{key}', [CartController::class, 'destroy'])->name('cart.destroy');
Route::post('/buy-now', [CartController::class, 'buyNow'])->name('cart.buy-now');
Route::post('/wishlist', [CartController::class, 'wishlist'])->name('wishlist.toggle');
Route::get('/track-order', [CheckoutController::class, 'track'])->name('orders.track');
Route::post('/track-order', [CheckoutController::class, 'lookup'])->name('orders.track.lookup');
Route::get('/search/suggestions', [StorefrontController::class, 'suggestions'])->name('search.suggestions');
Route::get('/checkout', [CheckoutController::class, 'show'])->name('checkout');
Route::post('/checkout', [CheckoutController::class, 'place'])->name('checkout.place');
Route::get('/orders/{order:order_number}/payment', [CheckoutController::class, 'payment'])->name('order.payment');
Route::post('/orders/{order:order_number}/payment/cod', [CheckoutController::class, 'chooseCod'])->name('order.payment.cod');
Route::get('/orders/success/{order:order_number}', [CheckoutController::class, 'success'])->name('order.success');
Route::get('/orders/{order:order_number}/invoice', [CheckoutController::class, 'invoice'])->name('order.invoice');
Route::post('/orders/{order:order_number}/wait-for-seller', [CheckoutController::class, 'waitForSeller'])->name('order.wait-for-seller');
Route::post('/orders/{order:order_number}/request-refund', [CheckoutController::class, 'requestRefund'])->name('order.request-refund');
Route::post('/orders/{order:order_number}/cancel', [CheckoutController::class, 'cancel'])->name('order.cancel');
Route::post('/orders/{order:order_number}/payment/razorpay', [CheckoutController::class, 'confirmRazorpayPayment'])->name('order.payment.razorpay.confirm');
Route::post('/orders/{order:order_number}/payment/razorpay-test', [CheckoutController::class, 'confirmRazorpayPayment'])->name('order.payment.razorpay-test');

Route::middleware(['auth', 'active', 'role:customer'])->group(function (): void {
    Route::post('/logout', [CustomerAuthController::class, 'logout'])->name('logout');
    Route::get('/complete-profile', [CustomerAuthController::class, 'completeProfile'])->name('profile.complete');
    Route::put('/complete-profile', [CustomerAuthController::class, 'updateProfile'])->name('profile.complete.update');

    Route::middleware('mobile.required')->group(function (): void {
        Route::get('/account', [CustomerAuthController::class, 'account'])->name('account.show');
        Route::put('/account/profile', [CustomerAuthController::class, 'updateProfile'])->name('account.profile.update');
        Route::put('/account/password', [CustomerAuthController::class, 'updatePassword'])->name('account.password.update');
        Route::post('/account/addresses', [CustomerAuthController::class, 'storeAddress'])->name('account.addresses.store');
        Route::put('/account/addresses/{address}/default', [CustomerAuthController::class, 'setDefaultAddress'])->name('account.addresses.default');
        Route::delete('/account/addresses/{address}', [CustomerAuthController::class, 'deleteAddress'])->name('account.addresses.destroy');
    });
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'active', 'role:super_admin'])->group(function (): void {
    Route::post('/logout', [AdminAuthController::class, 'logout'])->name('logout');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/approvals', ApprovalCenterController::class)->name('approvals.index');
    Route::get('/categories', [OperationsController::class, 'categories'])->name('categories.index');
    Route::get('/categories/create', [OperationsController::class, 'createCategory'])->name('categories.create');
    Route::post('/categories', [AdminCategoryController::class, 'store'])->name('categories.store');
    Route::get('/categories/{category}/edit', [AdminCategoryController::class, 'edit'])->name('categories.edit');
    Route::put('/categories/{category}', [AdminCategoryController::class, 'update'])->name('categories.update');
    Route::patch('/categories/{category}/status', [AdminCategoryController::class, 'updateStatus'])->name('categories.status.update');
    Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy'])->name('categories.destroy');
    Route::get('/products', [AdminProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [AdminProductController::class, 'create'])->name('products.create');
    Route::post('/products', [AdminProductController::class, 'store'])->name('products.store');
    Route::get('/products/{slug}/edit', [AdminProductController::class, 'edit'])->name('products.edit');
    Route::put('/products/{slug}', [AdminProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{slug}', [AdminProductController::class, 'destroy'])->name('products.destroy');
    Route::delete('/product-images/{image}', [AdminProductController::class, 'destroyImage'])->name('product-images.destroy');
    Route::get('/inventory', [OperationsController::class, 'inventory'])->name('inventory.index');
    Route::get('/orders', [OperationsController::class, 'orders'])->name('orders.index');
    Route::get('/orders/labels/dashboard', [ShippingLabelController::class, 'index'])->name('shipping-labels.index');
    Route::post('/orders/labels/bulk', [ShippingLabelController::class, 'bulk'])->name('shipping-labels.bulk');
    Route::get('/orders/labels/{label}', [ShippingLabelController::class, 'show'])->name('shipping-labels.show');
    Route::post('/orders/labels/{label}/regenerate', [ShippingLabelController::class, 'regenerate'])->name('shipping-labels.regenerate');
    Route::post('/orders/labels/{label}/print', [ShippingLabelController::class, 'print'])->name('shipping-labels.print');
    Route::get('/orders/labels/{label}/pdf', [ShippingLabelController::class, 'pdf'])->name('shipping-labels.pdf');
    Route::post('/orders/{order:order_number}/labels', [ShippingLabelController::class, 'generate'])->name('shipping-labels.generate');
    Route::put('/orders/{order:order_number}/location', [ShippingLabelController::class, 'updateLocation'])->name('shipping-labels.location.update');
    Route::get('/orders/{order:order_number}', [OperationsController::class, 'orderShow'])->name('orders.show');
    Route::get('/orders/{order:order_number}/invoice', [CheckoutController::class, 'adminInvoice'])->name('orders.invoice');
    Route::put('/orders/{order:order_number}/workflow', [OrderWorkflowController::class, 'update'])->name('orders.workflow.update');
    Route::get('/customers', [CustomerManagementController::class, 'index'])->name('customers.index');
    Route::get('/customers/exports', [CustomerManagementController::class, 'exports'])->name('customers.exports');
    Route::get('/customers/export', [CustomerManagementController::class, 'export'])->name('customers.export');
    Route::get('/customers/segments', [CustomerManagementController::class, 'segments'])->name('customers.segments');
    Route::get('/customers/abandoned-carts', [AbandonedCartController::class, 'index'])->name('customers.abandoned-carts.index');
    Route::get('/customers/abandoned-carts/{cart}', [AbandonedCartController::class, 'show'])->name('customers.abandoned-carts.show');
    Route::post('/customers/abandoned-carts/{cart}/dismiss', [AbandonedCartController::class, 'dismiss'])->name('customers.abandoned-carts.dismiss');
    Route::post('/customers/abandoned-carts/{cart}/mark-recovered', [AbandonedCartController::class, 'markRecovered'])->name('customers.abandoned-carts.mark-recovered');
    Route::get('/customers/whatsapp', [CustomerManagementController::class, 'communications'])->name('customers.whatsapp.index');
    Route::get('/customers/communications', [CustomerManagementController::class, 'communications'])->name('customers.communications.index');
    Route::post('/customer-communications/{communication}/open-whatsapp', [CustomerManagementController::class, 'openWhatsapp'])->name('customer-communications.open-whatsapp');
    Route::post('/customer-communications/{communication}/mark-sent', [CustomerManagementController::class, 'markCommunicationSent'])->name('customer-communications.mark-sent');
    Route::get('/customers/{customer}', [CustomerManagementController::class, 'show'])->name('customers.show');
    Route::put('/customers/{customer}/status', [CustomerManagementController::class, 'updateStatus'])->name('customers.status.update');
    Route::put('/customers/{customer}/consent', [CustomerManagementController::class, 'updateConsent'])->name('customers.consent.update');
    Route::get('/customers/{customer}/whatsapp', [CustomerManagementController::class, 'whatsapp'])->name('customers.whatsapp.compose');
    Route::post('/customers/{customer}/whatsapp', [CustomerManagementController::class, 'prepareWhatsapp'])->name('customers.whatsapp.prepare');
    Route::get('/settings/company', [SettingsController::class, 'company'])->name('settings.company');
    Route::put('/settings/company', [SettingsController::class, 'updateCompany'])->name('settings.company.update');
    Route::get('/settings/invoice', [SettingsController::class, 'invoice'])->name('settings.invoice');
    Route::put('/settings/invoice', [SettingsController::class, 'updateInvoice'])->name('settings.invoice.update');
    Route::get('/settings/tax', [SettingsController::class, 'tax'])->name('settings.tax');
    Route::post('/settings/tax/slabs', [SettingsController::class, 'storeTaxSlab'])->name('settings.tax-slabs.store');
    Route::put('/settings/tax/assignments', [SettingsController::class, 'updateTaxAssignments'])->name('settings.tax.assignments.update');
    Route::get('/settings/shipping', [SettingsController::class, 'shipping'])->name('settings.shipping');
    Route::put('/settings/shipping', [SettingsController::class, 'updateShipping'])->name('settings.shipping.update');
    Route::get('/settings/payments', [SettingsController::class, 'payments'])->name('settings.payments');
    Route::put('/settings/payments', [SettingsController::class, 'updatePayments'])->name('settings.payments.update');
    Route::get('/sellers', [SellerManagementController::class, 'index'])->name('sellers.index');
    Route::get('/sellers/commission-rules', [SellerManagementController::class, 'commissionRules'])->name('sellers.commissions.index');
    Route::post('/sellers/commission-rules', [SellerManagementController::class, 'storeCommissionRule'])->name('sellers.commissions.store');
    Route::get('/sellers/banners', [SellerManagementController::class, 'banners'])->name('sellers.banners.index');
    Route::post('/sellers/banners', [SellerManagementController::class, 'storeBanner'])->name('sellers.banners.store');
    Route::get('/sellers/{vendor}', [SellerManagementController::class, 'show'])->name('sellers.show');
    Route::put('/sellers/{vendor}/status', [SellerManagementController::class, 'updateStatus'])->name('sellers.status.update');
    Route::put('/sellers/{vendor}/bank', [SellerManagementController::class, 'updateBankStatus'])->name('sellers.bank.update');
    Route::get('/settlements', [SettlementReconciliationController::class, 'index'])->name('settlements.index');
    Route::get('/settlements/preview', [SettlementReconciliationController::class, 'preview'])->name('settlements.preview');
    Route::post('/settlements/generate', [SettlementReconciliationController::class, 'generate'])->name('settlements.generate');
    Route::get('/category-requests', [CategoryRequestController::class, 'index'])->name('category-requests.index');
    Route::put('/category-requests/{categoryRequest}', [CategoryRequestController::class, 'update'])->name('category-requests.update');
    Route::redirect('/settlements/category-requests', '/admin/category-requests')->name('settlements.category-requests.legacy');
    Route::get('/content', [MarketingController::class, 'index'])->name('content.index');
    Route::get('/content/create', [MarketingController::class, 'create'])->name('content.create');
    Route::post('/content', [MarketingController::class, 'store'])->name('content.store');
    Route::get('/content/{content}/edit', [MarketingController::class, 'edit'])->name('content.edit');
    Route::put('/content/{content}', [MarketingController::class, 'update'])->name('content.update');
    Route::patch('/content/{content}/status', [MarketingController::class, 'updateStatus'])->name('content.status.update');
    Route::delete('/content/{content}', [MarketingController::class, 'destroy'])->name('content.destroy');
    Route::get('/content/collections', [MarketingController::class, 'collections'])->name('content.collections.index');
    Route::post('/content/collections', [MarketingController::class, 'storeCollection'])->name('content.collections.store');
    Route::put('/content/collections/{collection}', [MarketingController::class, 'updateCollection'])->name('content.collections.update');
    Route::get('/settlements/{settlement}', [SettlementReconciliationController::class, 'show'])->name('settlements.show');
    Route::put('/settlements/{settlement}/status', [SettlementReconciliationController::class, 'transition'])->name('settlements.status.update');
    Route::post('/settlements/{settlement}/adjustments', [SettlementReconciliationController::class, 'adjustment'])->name('settlements.adjustments.store');
    Route::post('/settlements/{settlement}/manual-payment', [SettlementReconciliationController::class, 'markPaid'])->name('settlements.manual-payment.store');
    Route::get('/settings/{section}', [SettingsController::class, 'placeholder'])->name('settings.placeholder');
});

Route::prefix('seller')->name('seller.')->middleware(['auth', 'seller.profile'])->group(function (): void {
    Route::post('/logout', [SellerAuthController::class, 'logout'])->name('logout');
    Route::get('/status', [SellerOnboardingController::class, 'status'])->name('status');
    Route::get('/onboarding', [SellerOnboardingController::class, 'show'])->name('onboarding');
    Route::get('/onboarding/step/{step}', [SellerOnboardingController::class, 'step'])->name('onboarding.step');
    Route::post('/onboarding', [SellerOnboardingController::class, 'store'])->name('onboarding.store');
    Route::post('/onboarding/autosave', [SellerOnboardingController::class, 'autosave'])->name('onboarding.autosave');
    Route::get('/onboarding/plan', [SellerOnboardingController::class, 'showPlanSelection'])->name('onboarding.plan');
    Route::post('/onboarding/plan', [SellerOnboardingController::class, 'selectPlan'])->name('onboarding.plan.select');
    Route::post('/onboarding/submit-review', [SellerOnboardingController::class, 'submitForReview'])->name('onboarding.submit-review');
    Route::get('/onboarding/review', [SellerOnboardingController::class, 'review'])->name('onboarding.review');
    Route::post('/onboarding/review', [SellerOnboardingController::class, 'activateFromReview'])->name('onboarding.review.activate');
    Route::get('/onboarding/payment', [SellerOnboardingController::class, 'payment'])->name('onboarding.payment');
    Route::post('/onboarding/payment/retry', [SellerOnboardingController::class, 'retryPayment'])->name('onboarding.payment.retry');
    Route::post('/onboarding/payment/confirm', [SellerOnboardingController::class, 'confirmPayment'])->name('onboarding.payment.confirm');
    Route::get('/onboarding/success', [SellerOnboardingController::class, 'success'])->name('onboarding.success');

    Route::middleware(['seller.active', 'seller.onboarded'])->group(function (): void {
        Route::post('/publish', [SellerOnboardingController::class, 'publish'])->name('publish');
        Route::get('/dashboard', SellerDashboardController::class)->name('dashboard');
        Route::get('/products', [SellerProductController::class, 'index'])->name('products.index');
        Route::get('/products/create', [SellerProductController::class, 'create'])->name('products.create');
        Route::post('/products', [SellerProductController::class, 'store'])->name('products.store');
        Route::get('/products/{product}/edit', [SellerProductController::class, 'edit'])->name('products.edit');
        Route::put('/products/{product}', [SellerProductController::class, 'update'])->name('products.update');
        Route::delete('/product-images/{image}', [SellerProductController::class, 'destroyImage'])->name('product-images.destroy');
        Route::get('/inventory', [SellerInventoryController::class, 'index'])->name('inventory.index');
        Route::post('/inventory/{variant}/adjust', [SellerInventoryController::class, 'adjust'])->name('inventory.adjust');
        Route::get('/orders', [SellerOrderController::class, 'index'])->name('orders.index');
        Route::get('/orders/{order:order_number}', [SellerOrderController::class, 'show'])->name('orders.show');
        Route::put('/orders/{order:order_number}', [SellerOrderController::class, 'update'])->name('orders.update');
        Route::get('/categories', [SellerCategoryController::class, 'index'])->name('categories.index');
        Route::put('/categories', [SellerCategoryController::class, 'updateMarketplace'])->name('categories.update');
        Route::post('/category-requests', [SellerCategoryController::class, 'requestMarketplace'])->name('category-requests.store');
        Route::post('/categories/subcategories', [SellerCategoryController::class, 'storeSubcategory'])->name('categories.subcategories.store');
        Route::put('/categories/subcategories/{category}', [SellerCategoryController::class, 'updateSubcategory'])->name('categories.subcategories.update');
        Route::delete('/categories/subcategories/{category}', [SellerCategoryController::class, 'destroySubcategory'])->name('categories.subcategories.destroy');
        Route::get('/customers', [SellerModuleController::class, 'customers'])->name('customers.index');
        Route::get('/customers/{customerKey}', [SellerModuleController::class, 'customer'])->name('customers.show');
        Route::get('/payments', [SellerModuleController::class, 'payments'])->name('payments.index');
        Route::get('/earnings', SellerEarningsController::class)->name('earnings.index');
        Route::get('/settlements', [SellerSettlementController::class, 'index'])->name('settlements.index');
        Route::get('/settlements/{settlement}', [SellerSettlementController::class, 'show'])->name('settlements.show');
        Route::get('/settlements/{settlement}/statement', [SellerSettlementController::class, 'statement'])->name('settlements.statement');
        Route::put('/settlements', [SellerModuleController::class, 'updateSettlements'])->name('settlements.update');
        Route::get('/plans', [SellerModuleController::class, 'generic'])->defaults('module', 'plans')->name('plans.index');
        Route::post('/plans/renew', [SellerModuleController::class, 'renewPlan'])->name('plans.renew');
        Route::get('/shipping', [SellerModuleController::class, 'generic'])->defaults('module', 'shipping')->name('shipping.index');
        Route::put('/shipping', [SellerModuleController::class, 'updateShipping'])->name('shipping.update');
        Route::get('/labels', [SellerModuleController::class, 'generic'])->defaults('module', 'labels')->name('labels.index');
        Route::get('/marketing', [SellerModuleController::class, 'generic'])->defaults('module', 'marketing')->name('marketing.index');
        Route::get('/reports', [SellerModuleController::class, 'generic'])->defaults('module', 'reports')->name('reports.index');
        Route::get('/store-profile', [SellerModuleController::class, 'generic'])->defaults('module', 'store_profile')->name('store-profile');
        Route::put('/store-profile', [SellerModuleController::class, 'updateStoreProfile'])->name('store-profile.update');
        Route::get('/settings', [SellerModuleController::class, 'generic'])->defaults('module', 'settings')->name('settings.index');
        Route::put('/settings', [SellerModuleController::class, 'updateSettings'])->name('settings.update');
        Route::get('/support', [SellerModuleController::class, 'generic'])->defaults('module', 'support')->name('support.index');
    });
});
